/* A nonsense dataset */
var payload = {
  'proteins': [
    '1,2-alpha-L-fucosidase',
    '1,5-anhydro-D-fructose reductase',
    '1-phosphatidylinositol 4-kinase',
    '1-phosphofructokinase',
    '2\',3\'-cyclic-nucleotide 3\'-phosphodiesterase',
    '2-haloacid dehalogenase (configuration-inverting)',
    '2-hydroxychromene-2-carboxylate isomerase',
    '2-Methylcitrate dehydratase',
    '2-oxoglutarate carboxylase',
    '2-pyrone-4,6-dicarboxylate lactonase',
    '3-dehydroshikimate dehydratase (Major component )',
    '3-deoxy-manno-octulosonate-8-phosphatase',
    '3-galactosyl-N-acetylglucosaminide 4-alpha-L-fucosyltransferase',
    '3-(hydroxyamino)phenol mutase',
    '3-isopropylmalate dehydrogenase',
    '3-mercaptopyruvate sulfurtransferase',
    '3(or 17)beta-hydroxysteroid dehydrogenase',
    '3-phytase',
    '4-chlorobenzoyl-CoA dehalogenase',
    '4-oxalmesaconate hydratase',
    '(4S)-beta-phellandrene synthase',
    '5\'-nucleotidase',
    '5\'-nucleotidase (isoenzyme 5\'-NT-2)',
    '5\'-nucleotidase (isoenzyme 5\'-NT-4)',
    '6-Carboxyhexanoate-CoA ligase',
    '6-phosphofructo-2-kinase',
    '7-methylxanthosine synthase',
    'Acetolactate decarboxylase',
    'acetolactate synthase (isoform ALS II)',
    'Acetylcholinesterase (minor form)',
    'Acetylesterase',
    'Acetylxylan esterase (isoenzyme 1)',
    'Acetylxylan esterase (isoenzyme 3)',
    'Acetylxylan esterase (native)',
    'Acid phosphatase (Apase 2)',
    'Aconitate hydratase',
    'Acyl-CoA hydrolase',
    'Adenine phosphoribosyltransferase',
    'Adenosine kinase',
    'Adenosylcobinamide-phosphate guanylyltransferase',
    'Adenosylhomocysteinase',
    'Adenylate kinase (isoenzyme alpha)',
    'Alanine racemase',
    'Alanine transaminase (Isoform I)',
    'Alcohol dehydrogenase (NADP+)',
    'Alcohol oxidase',
    'Aldehyde dehydrogenase (NAD+)',
    'Aldehyde dehydrogenase (Pyrroloquinoline-quinone) (ADH I)',
    'Aldehyde dehydrogenase (Pyrroloquinoline-quinone) (ADH IIG)',
    'Aliphatic nitrilase',
    'Alkaline phosphatase',
    'Alliin lyase (Alliinase I)',
    'Alpha-agarase',
    'Alpha,alpha-trehalose-phosphate synthase (UDP-forming)',
    'Alpha-amino-acid esterase',
    'Alpha-amylase (alpha-I1)',
    'Alpha-amylase (Muscle)',
    'Alpha-galactosidase 2',
    'Alpha-galactosidase (Isoenzyme B1)',
    'Alpha-galactosidase (Isoenzyme B3)',
    'Alpha-galactosidase (isoenzyme M2)',
    'Alpha-glucosidase',
    'Alpha-glucuronidase',
    'Alpha-L-fucosidase (isoform I)',
    'Alpha-L-fucosidase (possible minor form)',
    'Alpha-N-acetylgalactosaminidase',
    'Alpha-neoagaro-oligosaccharide hydrolase',
    'Amidase',
    'Aminolevulinate transaminase',
    'Aminopeptidase Ey',
    'Aminopeptidase S',
    'Anthocyanidin 3-O-glucosyltransferase',
    'Apyrase',
    'Apyrase (isotype P1)',
    'Apyrase (isotype P3)',
    'Arabinan endo-1,5-alpha-L-arabinosidase',
    'Argininosuccinate lyase',
    'Aryl-alcohol oxidase',
    'Aryldialkylphosphatase',
    'Aryldialkylphosphatase (recombinant His6-tagged OPH)',
    'Aryl sulfotransferase',
    'Asparagine-tRNA ligase',
    'Aspartate-prephenate aminotransferase (minor fraction)',
    'Aspartate transaminase (form I)',
    'Aspartate transaminase (isoenzyme 1)',
    'Aspartate transaminase ( isoenzyme A)',
    'Aspartate transaminase (Mitochondrial)',
    'Baicalein 7-O-glucuronosyltransferase',
    'Benzaldehyde dehydrogenase (NADP+)',
    'Beta-amylase',
    'Beta-amylase (isoenzyme 50KCBA2)',
    'Beta-amylase (isoenzyme 50KCBA4)',
    'Beta-fructofuranosidase',
    'Beta-fructofuranosidase (Alkaline invertase isozyme IT I)',
    'Beta-fructofuranosidase (S-form)',
    'Beta-galactosidase',
    'Beta-galactosidase II',
    'Beta-galactoside alpha-2,6-sialyltransferase',
    'Beta-glucosidase (isoform 1)',
    'Beta-glucuronidase',
    'Beta-ketoacyl-acyl-carrier-protein synthase III',
    'Beta-lactamase (Bla-A)',
    'Beta-lactamase (CARB-3)',
    'Beta-lactamase (CTX-M-26)',
    'Beta-lactamase (Mutant enzyme P51L)',
    'Beta-lactamase (PSE-I)',
    'Beta-lactamase (TEM-8)',
    'Beta-mannosidase (isozyme GM-1)',
    'Beta-mannosidase (isozyme OT-1)',
    'Beta-primeverosidase',
    'Beta-ureidopropionase (Recombinant beta-UP)',
    'Biotin-independent malonate decarboxylase',
    'Bontoxilysin',
    'Bromide peroxidase',
    'Bromide peroxidase (BPO 2)',
    'Bromide peroxidase (nonhaem-type bromoperoxidase BPO 1a)',
    'Bromide peroxidase (nonhaem-type bromoperoxidase BPO 3)',
    'Butyryl-CoA dehydrogenase',
    'Caffeine synthase',
    'cAMP-dependent protein kinase (regulatory subunit Rmyt1)',
    'Carbamate kinase',
    'Carbonyl reductase (NADPH)',
    'Carboxylesterase (AB010635)',
    'Carboxylesterase (D50580)',
    'Carboxylesterase (ES3)',
    'Carboxylesterase (ME1)',
    'Carboxylesterase (ME3)',
    'Carboxypeptidase C',
    'Carboxypeptidase C (isoenzyme MpiCP-2)',
    'Catalase',
    'Catechol 2,3-dioxygenase',
    'Cathepsin D',
    'Cathepsin X',
    'Cellulase (endoglucanase EG25)',
    'Cellulase (endoglucanase EG44)',
    'Cellulase (endoglucanase EG51)',
    'Cellulose 1,4-beta-cellobiosidase',
    'Cellulose 1,4-beta-cellobiosidase (CBHII)',
    'Cellulose 1,4-beta-cellobiosidase (Cel7A)',
    'Ceramidase',
    'Chitinase',
    'Chitinase 2',
    'Chitinase  (GAC2)',
    'Chitinase (isoenzyme HoChiB)',
    'Chitinase ( isoform Chi-56 )',
    'Chitinase (isozymes ChiA)',
    'Chitinase (isozymes ChiC)',
    'Chitosanase',
    'Chitosanase (enzyme BCVC-1)',
    'Chitosanase (enzyme BCVC-3)',
    'Chitosanase (enzyme BCVC-5)',
    'Chitosanase PSC-I',
    'Chitosanase PSC-III',
    'Chlorogenate hydrolase',
    'Cholesterol oxidase',
    'Choline kinase (acidic isoform)',
    'Choline kinase (isoenzyme B)',
    'Choline kinase (isoform CKI)',
    'Choloylglycine hydrolase',
    'Chondroitin B lyase',
    'Chondroitin-sulfate-ABC exolyase',
    'Chondroitin-sulfate-ABC exolyase (isoenzyme II)',
    'Chymosin',
    'Chymotrypsin I',
    'Chymotrypsin (isoform Kh1)',
    'Chymotrypsin (isoform Kh3)',
    'Citrate (Si)-synthase (mutant D317G)',
    'Citrate (Si)-synthase (mutant H187Q)',
    'Citrate (Si)-synthase (mutant W115F)',
    'Citrate (Si)-synthase (mutant W245F)',
    'Citrate (Si)-synthase (wild-type)',
    'Coniferin beta-glucosidase',
    'Creatine kinase (dimeric form)',
    'Creatine kinase (Dimeric ubiquitous isoform)',
    'Creatine kinase (enzyme variant II)',
    'Creatine kinase (enzyme variant IV)',
    'Creatine kinase (isoform MM1)',
    'Creatine kinase (isoform MM3)',
    'Creatine kinase (Octameric sarcomeric isoform)',
    'Cycloisomaltooligosaccharide glucanotransferase',
    'Cyclomaltodextrin glucanotransferase',
    'Cysteine dioxygenase',
    'Cytokinin dehydrogenase',
    'D-amino-acid oxidase',
    'D-amino-acid oxidase (holoenzyme )',
    'D-arabitol-phosphate dehydrogenase',
    'Deacetoxycephalosporin-C synthase',
    'Deoxyguanosine kinase (Mitochondrial)',
    'Deoxyribonuclease I',
    'Deoxyribonuclease I (isozyme A)',
    'Dephospho-[reductase kinase] kinase',
    'Dextranase (isoenzyme 2)',
    'Dextranase (isoenzyme 4)',
    'Dextranase (isoenzyme 6)',
    'Diacetyl reductase [(S)-acetoin forming]',
    'Diaminobutyrate decarboxylase',
    'Dihydrofolate reductase',
    'Dihydroorotase',
    'Dipeptidyl-peptidase II',
    'Diphosphomevalonate decarboxylase',
    'DNA-3-methyladenine glycosylase I',
    'DNA-(apurinic or apyrimidinic site) lyase',
    'Dodecenoyl-CoA isomerase',
    'D(-)-tartrate dehydratase',
    'D-xylose reductase',
    'D-xylose reductase 2',
    'Ectoine synthase',
    'Endo-1,4-beta-xylanase',
    'Endo-1,4-beta-xylanase (isoform XynC)',
    'Endo-1,4-beta-xylanase (isozyme Ib)',
    'Endo-1,4-beta-xylanase (isozyme XA-1)',
    'Endo-1,4-beta-xylanase (Wild-type)',
    'Endo-1,4-beta-xylanase (Xyl1-3)',
    'Endo-1,4-beta-xylanase (Xyl2)',
    'Endo-1,4-beta-xylanase (Xyl6-6)',
    'Estrone sulfotransferase',
    'Exo-poly-alpha-galacturonosidase',
    'Fatty-acyl-ethyl-ester synthase',
    'Ferredoxin-NADP+ reductase',
    'Ferredoxin-NADP+ reductase (Isozyme FNR-B)',
    'Feruloyl esterase',
    'Feruloyl esterase C',
    'Feruloyl esterase (type B enzyme)',
    'Fibroblast activation protein alpha subunit',
    'Flavone synthase',
    'Flavonol 7-O-beta-glucosyltransferase',
    '[formate-C-acetyltransferase]-activating enzyme',
    'Fructan beta-fructosidase',
    'Fructokinase I (2 components)',
    'Fructokinase I (Polypeptide 1)',
    'Fruit bromelain',
    'Galactose oxidase',
    'Galacturan 1,4-alpha-galacturonidase',
    'Gelatinase A',
    'Gentamicin 2\'\'-nucleotidyltransferase (isoform II)',
    'Gibberellin 2beta-dioxygenase',
    'Gingipain R2 (isoform I)',
    'Gingipain R2 (isoform III)',
    'Gingipain R2 (RgpB isozyme II)',
    'Gingipain R (RGP-A)',
    'Glucan 1,3-alpha-glucosidase',
    'Glucan 1,4-alpha-glucosidase (isozyme GA-I)',
    'Glucan 1,4-alpha-maltohydrolase',
    'Glucan endo-1,3-beta-D-glucosidase',
    'Gluconate 2-dehydrogenase (cj0414)',
    'Glucose 1-dehydrogenase',
    'Glucose-1-phospho-D-mannosylglycoprotein phosphodiesterase',
    'Glucose-6-phosphate dehydrogenase (G6PDH-1)',
    'Glucose oxidase',
    'Glucuronate-2-sulfatase',
    '[glutamate-ammonia-ligase] adenylyltransferase',
    'Glutamate dehydrogenase [NAD(P)+]',
    'Glutaminase',
    'Glutamyl-tRNA reductase',
    'Glutathione-disulfide reductase',
    'Glutathione synthase (Isozyme GSHS1)',
    'Glutathione transferase',
    'Glyceraldehyde-3-phosphate dehydrogenase (NADP+)',
    'Glycerol-1-phosphatase (Gpp1)',
    'Glycerol-3-phosphate dehydrogenase [NAD(P)+]',
    'Glycine/sarcosine/dimethylglycine N-methyltransferase(α subunit)',
    'Glycine/sarcosine/dimethylglycine N-methyltransferase(γ subunit)',
    'Glycochenodeoxycholate sulfotransferase',
    'Guanylate kinase',
    'Heparin lyase',
    'Hesperidin 6-O-alpha-L-rhamnosyl-beta-D-glucosidase',
    'Hexokinase A',
    'Hexokinase B2',
    'Hexokinase C2',
    'Hexokinase Ia',
    'Hexokinase Ib',
    'Hexokinase Ic',
    'Hexokinase III',
    'Histidine decarboxylase (alpha)',
    'Histolysain',
    'Hyaluronate lyase',
    'Hyaluronoglucosaminidase (Isozyme NNH1)',
    'Hydantoin racemase',
    'Hydrogenase (acceptor)',
    'Hydroxydechloroatrazine ethylaminohydrolase',
    'Hydroxymethylglutaryl-CoA lyase (peroxisomal)',
    'Indoleamine 2,3-dioxygenase (Recombinant)',
    'Inosine kinase',
    'Inositol-3-phosphate synthase',
    'Inulinase',
    'Isocitrate dehydrogenase (NADP+) Isoenzyme ICDH-1',
    'Isocitrate dehydrogenase (NADP+) Isoenzyme ICDH-3',
    'Isoflavone 7-O-methyltransferase',
    'Isoprene synthase',
    'Juvenile-hormone esterase (Major form)',
    'Juvenile-hormone esterase (Recombinant)',
    'Ketohexokinase',
    'Kievitone hydratase',
    'Kumamolysin',
    'Laccase',
    'Laccase (B)',
    'Laccase (Lac II)',
    'L-amino-acid oxidase',
    'Leghemoglobin reductase',
    'Leukocyte elastase',
    'Leukotriene-A4 hydrolase',
    'Licheninase',
    'L-iditol 2-dehydrogenase 2',
    'L-iditol 2-dehydrogenase 6',
    'Linoleate 9S-lipoxygenase',
    'L-lysine oxidase',
    'Lupanine hydroxylase (reduced enzyme)',
    'Lysophospholipase (LPL1)',
    'Lysozyme',
    'Malate dehydrogenase',
    'Malate dehydrogenase (oxaloacetate-decarboxylating [NADP+]1',
    'Malate dehydrogenase (Quinone)',
    'Maltose-6\'-phosphate glucosidase',
    'Manganese peroxidase (MnP1)',
    'Manganese peroxidase (MnP4)',
    'Mannan endo-1,4-beta-mannosidase (ManA)',
    'Mannitol-1-phosphatase',
    'Mannitol 2-dehydrogenase (NADP+)',
    'Mannosylglycerate synthase',
    'Mannosyl-oligosaccharide 1,3-1,6-alpha-mannosidase',
    'Mannosyl-oligosaccharide 1,3-1,6-alpha-mannosidase (2)',
    'Mason-Pfizer monkey virus proteinase (p12)',
    'Mason-Pfizer monkey virus proteinase (p17)',
    'Membrane dipeptidase',
    'Methane monooxygenase (α subunit)',
    'Methane monooxygenase (γ subunit)',
    'Methanesulfonate monooxygenase (Two-component hydroxylase α sub.)',
    'Methionine adenosyltransferase',
    'Methionine gamma-lyase EhMGL2',
    'Methionine gamma-lyase (Recombinant EhMGL2)',
    'Methyl halide transferase',
    'Methylmalonyl-CoA carboxytransferase (Subunit 12S)',
    'Methylmalonyl-CoA carboxytransferase (Subunit 5S)',
    'Mevalonate kinase',
    'Monodehydroascorbate reductase (NADH)',
    'Mucorpepsin',
    'N-acetylneuraminate lyase',
    'N-acylneuraminate cytidylyltransferase',
    'NADH dehydrogenase (Quinone)',
    'NAD+ kinase',
    'NAD+ synthase',
    'Nitrile hydratase',
    'Nitrile hydratase (beta subunit)',
    'Non-specific polyamine oxidase',
    'Nucleoside-diphosphate kinase B',
    'Nucleotide diphosphokinase',
    'Oleoyl-[acyl-carrier-protein] hydrolase (PO-FAT)',
    'Oligopeptide-transporting ATPase (OppA2)',
    'Oligopeptide-transporting ATPase (OppA4)',
    'Oligoxyloglucan beta-glycosidase',
    'O-succinylbenzoate-CoA ligase',
    'Palmitoyl-CoA hydrolase',
    'Pancreatic ribonuclease',
    'Pantothenate kinase A',
    'Papain',
    'Pectate lyase',
    'Pectate lyase II',
    'Pectate lyase PelA',
    'Pectate lyase PelC',
    'Pectate lyase PelE',
    'Pectinesterase 1',
    'Pectinesterase 3',
    'Pectinesterase II',
    'Pectinesterase (luPME3)',
    'Pectin lyase',
    'Penicillin amidase (PA5.3)',
    'Pepsin A',
    'Peroxidase (Anionic)',
    'Peroxidase - Tb(III) complex',
    'Phenol 2-monooxygenase (PheA1)',
    'Phenylacetate-CoA ligase',
    'Phenylalanine ammonia-lyase (PAL-II)',
    'Phenylalanine/tyrosine ammonia-lyase',
    'Phosphoenolpyruvate carboxykinase (GTP)',
    'Phosphogluconate dehydrogenase (decarboxylating)',
    'Phosphoglycerate kinase A (Glycosomal isozyme)',
    'Phosphoglycerate kinase (Chloroplastic)',
    'Phosphoglycerate kinase (New Guinea population variant)',
    'Phosphoglycerate kinase (Truncated glycosomal isozyme)',
    'Phosphoglycolate phosphatase',
    'Phospholipase A2 (BaPLA2III)',
    'Phospholipase A2 (lm-PLA2-II)',
    'Phospholipase A2 (LmTX-II)',
    'Phospholipase A3 (BaPLA2I)',
    'Phospholipid-hydroperoxide glutathione peroxidase',
    'Phosphonate dehydrogenase (Mutant enzyme E175A/A176R)',
    'Phosphonate dehydrogenase (Wild type)',
    'Phosphopentomutase',
    'Phosphopyruvate hydratase',
    'Photinus-luciferin 4-monooxygenase (ATP-hydrolysing)',
    'Phytepsin (Cynarase B)',
    'Picornain 3C',
    'Poly(3-hydroxyoctanoate) depolymerase',
    'Polyenoic fatty acid isomerase',
    'Polyphosphate-glucose phosphotransferase',
    'Polyribonucleotide nucleotidyltransferase',
    'Pprotein-glutamate methylesterase',
    'Prostasin',
    'Protease lasA',
    'Proteinase P15',
    'Protein-glutamine gamma-glutamyltransferase',
    'Protein-L-isoaspartate(D-aspartate) O-methyltransferase (PIMT2)',
    'Pseudotropine acyltransferase',
    'Purine nucleosidase',
    'Pyranose oxidase',
    'Pyrethroid hydrolase E1',
    'Pyrethroid hydrolase E3',
    'Pyruvate decarboxylase (1)',
    'Pyruvate kinase',
    'Pyruvate kinase (M1)',
    'Pyruvate kinase (PK-aerobic)',
    'Pyruvate, phosphate dikinase (CyPPDK 2)',
    'Quercetin-3,3\'-bissulfate 7-sulfotransferase II',
    '(R)-2-haloacid dehalogenase',
    'Rhamnogalacturonan endolyase',
    'Rhamnogalacturonan hydrolase',
    'Ribonuclease D',
    'Ribonuclease T2',
    'Ribonuclease T2 (Rnase LV-2)',
    'Ribonuclease T3',
    'Ribose-5-phosphate isomerase',
    'Ribose-phosphate diphosphokinase (Mutant enzyme)',
    'Ribose-phosphate diphosphokinase (PRSII)',
    'Ribulose-bisphosphate carboxylase (Small chain)',
    'Ribulose-phosphate 3-epimerase (Wild type)',
    'rRNA N-glycosylase',
    'rRNA N-glycosylase (beta-pisavin)',
    'rRNA N-glycosylase (Cinnamomin 1)',
    '(R)-specific secondary alcohol dehydrogenase',
    '(S)-2-haloacid dehalogenase',
    '(S)-coclaurine-N-methyltransferase',
    'Sedolisin',
    'Senecionine N-oxygenase',
    'Serralysin',
    'S-formylglutathione hydrolase',
    'Sialate O-acetylesterase',
    'S-methyl-5\'-thioadenosine phosphorylase',
    '(S)-norcoclaurine synthase',
    'Sorbose reductase',
    'Sphingomyelin deacylase',
    '(S,S)-butanediol dehydrogenase',
    'Stem bromelain (Isozyme SBA/a variant 2)',
    'Steroid 15beta-monooxygenase',
    'Sterol 3beta-glucosyltransferase',
    'Steryl-sulfatase',
    'Subtilisin',
    'Subtilisin (KV71)',
    'Succinate-CoA ligase (ADP-forming)',
    'Sulfate adenylyltransferase',
    'Sulfate adenylyltransferase (ATPSm)',
    'Superoxide dismutase (Fe-SOD/SodB)',
    'Superoxide dismutase (Mn-SOD/SodA)',
    'Superoxide dismutase (Recombinant enzyme)',
    'Superoxide dismutase (SODII)',
    'Superoxide dismutase (SODIV)',
    'Tartrate decarboxylase',
    'Terephthalate 1,2-dioxygenase (beta subunit)',
    'Thiamine-diphosphate kinase',
    'Thioglucosidase',
    'Thiosulfate sulfurtransferase',
    'Transaldolase',
    'Trans-o-hydroxybenzylidenepyruvate hydratase-aldolase B',
    'tRNA adenylyltransferase',
    'Trypsin A',
    'Trypsin C',
    'Trypsin ST-2',
    'Trypsin TLE I',
    'Tryptase',
    'Tyrosine-arginine ligase',
    'Tyrosine phenol-lyase',
    'Tyrosine-tRNA ligase',
    'UDP-N-acetylglucosamine 6-dehydrogenase',
    'UMP/CMP kinase',
    'Uracil-DNA glycosylase',
    'Versatile peroxidase (MP-1)',
    'Versatile peroxidase (PS1)',
    'Versatile peroxidase (PS3)',
    'Xaa-Xaa-Pro tripeptidyl-peptidase',
    'Xanthine dehydrogenase',
    'Xylan 1,4-beta-xylosidase (xylan-inducible)',
    'Xylan alpha-1,2-glucuronosidase',
    'Xyloglucan-specific endo-beta-1,4-glucanase',
    'Xyloglucan:xyloglucosyl transferase',
  ],
  'latin': [
    'acaulis',
    'acutus',
    'agrestis',
    'albopictus',
    'albus',
    'americanus',
    'amphi',
    'ampulla',
    'anthropos',
    'apis',
    'aquaticus',
    'arborescens',
    'archaeos',
    'arctos',
    'argentatus',
    'arthron',
    'arvensis',
    'astron',
    'atropurpureum',
    'aureomarginata',
    'aureus',
    'australis',
    'baccatus',
    'baccatus',
    'blandus',
    'blandus',
    'borealis',
    'brachion',
    'brachiopoda',
    'brachycephalus',
    'brachys',
    'bradys',
    'branchia',
    'branchiopoda',
    'brevis',
    'caecus',
    'caeruleus',
    'canadensis',
    'canescens',
    'canis',
    'canus',
    'cauda',
    'caulos',
    'cephale',
    'ceps',
    'ceros',
    'cestus',
    'chilensis',
    'chloros',
    'chroma',
    'cneme',
    'cola',
    'corax',
    'coronatus',
    'costatus',
    'crass',
    'cristatus',
    'crocos',
    'cyanos',
    'dactylos',
    'deca',
    'decem',
    'derma',
    'di',
    'didelphis',
    'dino',
    'diplo',
    'disc',
    'dodeca',
    'dolicho',
    'domesticus',
    'dorsum',
    'dulcis',
    'eburneus',
    'echinatus',
    'echinos',
    'edulis',
    'elatior',
    'electr',
    'elegans',
    'enanti',
    'ennea',
    'ensatus',
    'ensi',
    'erectus',
    'erion',
    'erosus',
    'erythropoda',
    'erythros',
    'familiaris',
    'felis',
    'flavus',
    'flor',
    'folium',
    'fulvus',
    'fuscus',
    'gaster',
    'geo',
    'glabra',
    'glycys',
    'gyrinos',
    'haema',
    'hali',
    'haplo',
    'hedra',
    'heli',
    'hexa',
    'hippo',
    'hirsutus',
    'homo',
    'hortensis',
    'hydro',
    'hyper',
    'hypo',
    'indicus',
    'kestos',
    'lactiflora',
    'lateralis',
    'latus',
    'lepis',
    'lepton',
    'lepus',
    'leucos',
    'lineatus',
    'luteus',
    'macro',
    'maculatus',
    'major',
    'malabaricus',
    'mauro',
    'maximus',
    'megas',
    'melano',
    'mephitis',
    'micro',
    'microphylla',
    'minimus',
    'minor',
    'mono',
    'montanus',
    'morpho',
    'mys',
    'nanos',
    'nona',
    'nothos',
    'notos',
    'novaehollandiae',
    'novaeseelandiae',
    'noveboracensis',
    'novem',
    'obscurus',
    'occidentalis',
    'ocean',
    'octo',
    'oeso',
    'officinalis',
    'oleum',
    'ophis',
    'ops',
    'opsis',
    'orientalis',
    'ortho',
    'pachy',
    'palustris',
    'pan',
    'parvus',
    'pedi',
    'pelag',
    'penn',
    'pennatus',
    'penta',
    'petra',
    'phago',
    'pholis',
    'phyllo',
    'physi',
    'phyto',
    'pictus',
    'platy',
    'poly',
    'praecox',
    'pratensis',
    'protos',
    'pseudes',
    'pter',
    'pubescens',
    'pulchellus',
    'punctatus',
    'pygmaeus',
    'quadifolia',
    'quadriflora',
    'repandus',
    'repens',
    'reptans',
    'rhis',
    'rhiza',
    'rhynchos',
    'rhyti',
    'rostra',
    'rostralis',
    'ruber',
    'rufus',
    'sanguis',
    'sapiens',
    'sativus',
    'saura',
    'septem',
    'silvestris',
    'sinensis',
    'specios',
    'sperma',
    'sphen',
    'stoma',
    'striatus',
    'strictus',
    'suchos',
    'tardus',
    'tele',
    'tenuis',
    'tetra',
    'tinctorius',
    'tomentosus',
    'tres',
    'trich',
    'triquetrus',
    'troglodytes',
    'unus',
    'ura',
    'variabilis',
    'variegatus',
    'velocis',
    'velox',
    'ventralis',
    'vernus',
    'verrucosus',
    'versicolor',
    'verus',
    'villosus',
    'viridis',
    'virosus',
    'volans',
    'vulgaris',
    'xanthos',
    'zygos'
  ],
  'organs': [
    '115 kDa polypeptide',
    '50kDa polypeptide',
    '67kDa polypeptide',
    'Abomasal tissue',
    'Adrenal gland',
    'Adult',
    'Anterior pituitary gland',
    'Aortic smooth muscle, heart, kidney, mesenteric artery',
    'ATCC 13368',
    'ATCC KL412',
    'ATCC KL515',
    'Blood, fibroblast, mononuclear cell',
    'Bone marrow',
    'Brain, heart',
    'Brain, kidney, liver, spermatozoon, testis',
    'Breast cancer cell, mammary epithelial cell',
    'Breast muscle (beta subunit)',
    'Bronchus, colon, kidney, liver, lung, pancreas, salivary gland, seminal plasma, urine',
    'Callus',
    'Callus, hypocotyl',
    'CBS 3',
    'Cecum',
    'Cell surface',
    'Cell suspension culture, leaf',
    'Cerebrum',
    'CHO cell-derived rhGAA',
    'CHO cell, lysosome',
    'Colon, small intestine',
    'Cortex',
    'Cotyledon, hypocotyl, seedling',
    'Cotyledon (peroxisomal membrane)',
    'Culture filtrate',
    'culture supernatant',
    'cv. Snowden MTs',
    'Cytoplasm',
    'Cytoplasm, inclusion body',
    'Cytosolic',
    'Cytosol, mitochondrion',
    'Digestive gland, hepatopancreas',
    'DSM 50135',
    'E-16',
    'Egg yolk',
    'Embryo',
    'Embryo, leaf, meristem, root, silique (plastid)',
    'Endosperm',
    'Endosperm, radicle, seed',
    'Enzyme form of malathion-sensitive insects',
    'Epicotyl, internode, radicle, stem',
    'Epidermis, leaf, secretory cell',
    'Epididymis',
    'Erythrocyte',
    'Erythrocyte, placenta',
    'Erythrocytes (Newborn)',
    'Extracellular enzyme',
    'Fibre tract, gonad, salivary gland, trachea',
    'Flavedo, fruit',
    'Flower bud, leaf, seed',
    'Flower, fruit, vegetative cell',
    'Foetal erythrocytes',
    'Fruit',
    'Fruitbody',
    'Fruit, juice',
    'Fruit (Membrane-bound)',
    'Gizzard (smooth muscle)',
    'Glycosome',
    'H-804',
    'Haemolymph',
    'HB8',
    'Heart and Kidney',
    'Heart, Mitochondria',
    'Hepatoma cell',
    'Hepatopancreas cytosol',
    'HT-1080 cell',
    'IFO 0173',
    'IFO 4033',
    'Intestine',
    'Intracellular enzyme',
    'K-12',
    'Kidney, Brain , Skeletal muscle, Liver',
    'Kidney, liver',
    'KT12',
    'Larvae',
    'Larva, midgut',
    'Latex',
    'Leaf',
    'Leaf, chloroplast',
    'Leaf (Chloroplast stroma)',
    'Leaf (Hypoderma, epidermis, cell walls)',
    'Leaf, peroxisomal matrix',
    'Leaf, petal, pith, root, stamen, stem cortex, xylem',
    'Leaf, root',
    'Leaf, root, seedling',
    'Leaf, seedling',
    'Leaf (Soluble form)',
    'Leaf, thylakoid membrane',
    'Leaf (TISIalphapsi)',
    'Leaf (TISIIalphaomega)',
    'Leaf (TISIIbetapsi)',
    'Leaf (TISIIIalphapsi)',
    'Leaf, tuber',
    'Leaf (young)',
    'Lens (Major enzyme form)',
    'Liver',
    'Liver (beta subunit)',
    'Liver cytosol',
    'Liver, Golgi membrane',
    'Liver microsomes',
    'Liver (Mitochondria)',
    'Liver (Mitochondrial matrix)',
    'LT2',
    'Lung',
    'Magnum region of the oviduct',
    'Membrane enzyme',
    'MH-K1',
    'Midgut',
    'Mitochondrial membrane',
    'Muscle',
    'Mutant strain PN-120',
    'Mycellum',
    'N176',
    'NCIM 1605',
    'Neuron',
    'NRRL 26517',
    'NRRL B-3693',
    'Oocyte',
    'Pal2',
    'PCC 7120',
    'Periplasm',
    'Placental enzyme',
    'Pollen grain, pollen tube',
    'Promastigote',
    'Pro-peptide mutant T206P',
    'Pulmonary artery smooth muscle',
    'Pupa',
    'RC 1071',
    'Recombinant enzyme (Leaf chloroplast)',
    'Reticulocyte',
    'Rhizome',
    'Root (Glomus mosseae/Glomus intraradices infection)',
    'Root, seedling',
    'Salivary gland',
    'Sclerotium',
    'Seed',
    'Seedling',
    'Semen',
    'Shoot',
    'Skeletal muscle',
    'Skin',
    'Soluble form',
    'Spermatozoon, testis',
    'Spleen and ovary',
    'Stem',
    'Stomach',
    'strain 150-1',
    'strain 18',
    'strain 3-19',
    'strain 5D1A',
    'strain A11',
    'strain A3(2)',
    'strain AS59',
    'strain ATCC 23357',
    'strain ATCC 34628',
    'strain BG214',
    'strain BRFM 131',
    'strain CBS 375.48',
    'strain CDBB531',
    'strain CECT 2413',
    'strain CQMa102',
    'strain DSM 20016',
    'strain E, ATCC 30005',
    'strain ECU1010',
    'strain HJ-15',
    'strain HY-12',
    'strain IMV 3011',
    'strain JZ-1',
    'strain KJ-72',
    'strain L1',
    'strain LKY-7',
    'strain M-105',
    'strain MIUG 16',
    'strain MTCC 5113',
    'strain MYA-1019, mycelium',
    'strain NCIM 1207',
    'strain NRRL 1894',
    'strain P4-N',
    'strain PAC1R',
    'strain RAG-1',
    'strain S38',
    'strain SO113',
    'strain T7',
    'strain TK-6',
    'strain UHH 1-13-18-4',
    'strain VTRM1',
    'strain WS',
    'strain YJ016',
    'strain ZD11',
    'str. KT2440',
    'T206G and T206G/S213G/T219G',
    'Tachyzoite',
    'TH6-2',
    'Thymus',
    'Trophozoite, cytosol',
    'Tuber',
    'Uterus',
    'Venom',
    'Wild type',
    'Xylem (2 year old Pinus contorta)',
    'ZD-8'
  ],
  'methods': [
    'Ampho<line electrophoresis',
    'Analytical gel isoelectric focusing',
    'Analytical isoelectric focusing',
    'Carrier-free isoelectric focusing',
    'Column isoelectric focusing',
    'Density gradient isoelectric focusing',
    'Disc electrophoresis',
    'Disc gel electrophoresis',
    'Electrofocusing',
    'Electrophoresis',
    'Electrostatic Focusing',
    'Gel electrophoresis',
    'Gel isoelectric focusing',
    'Isoelectric density gradient electrophoresis',
    'Isoelectric focusing',
    'Isoelectric focusing in polyacrylamide gel',
    'Isoelectric focusing in polyacrylamide gels',
    'Isoelectric focusing on acrylamide gel',
    'Isoelectric Focusing with a Carrier Ampholyte',
    'Isoelectric fractionation',
    'Isoelectrofocusing',
    'LKB apparatus',
    'LKB electrofocusing apparatus',
    'Measurement with an antimony microelectrode',
    'Microisoelectric focusing on polyacrylamide gel',
    'Polyacrylamide disc electrophoresis',
    'Polyacrylamide gel electrofucusing',
    'Polyacrylamide gel isoelectric focusing',
    'Preparative isoelectric focusing',
    'SDS disc electrophoresis',
    'SDS gel electrophoresis',
    'Stationary electrolysis',
    'Thin-layer isoelectric focusing',
    'To be confirmed',
    'Vesterberg and Svensson method'
  ],
  'notes': [
    'Acidic and basic forms of this protein',
    'alpha subunit only;unrewieved',
    'Available for different types of strain B',
    'Available for many strains of E.coli',
    'Available for numerous strains of influenza virus, but not this spefic one',
    'Available for two protien chains',
    'Currently not reviewed',
    'Currently Not reviewed',
    'Currently not reviewed nor a full sequence',
    'Currently not reviewed, only a fragment of sequence',
    'Currently only a fragement and not reviewed',
    'Currently only a fragment and not reviewed',
    'Listed for mutiple strains, none listed as R1 but it may be classed as something else',
    'listed simply as cockroach, not specified. However: http://www.uniprot.org/uniprot/O18598',
    'Listed simply as S. aureus, not sure as to whether it’s the same for all strains or whether it differs',
    'Listed under multiple strains of E. Coli',
    'Many nitrogenase proteins available',
    'Many subunits and different types are showing on Uniprot. The type of PK is not given in the original text',
    'Many subunits are showing on Uniprot',
    'Mitochondrial and cytoplasmic forms, unclear which was analysed in original paper',
    'Multiple forms are listed on this page',
    'Multiple forms available',
    'Multiple forms of protein',
    'Multiple Forms of protein',
    'Multiple forms of protein, from multiple strains of E.coli',
    'Multiple forms of protein listed',
    'Multiple forms of Protein Listed',
    'multiple forms of the DDT dehydrochlorinase were used',
    'multiple forms of the protein listed',
    'multiple proteases listed; not specified which one was used in the original experiment',
    'Multiple protein forms',
    'Multiple subunits and chains',
    'Multiple subunits available',
    'Multiple types of endonucleases are showing on Uniprot;',
    'Multiple β-crystallins available',
    'Multiple γ-Crystallins available',
    'No A or B varities just one protein',
    'Not listed in letter form on uniprot listed as alpha, beta etc',
    'Not listed in letter form on uniprot listed as alpha, beta etc. Causes mild hemolytic anemia',
    'Not listed in letter form on uniprot listed as alpha, beta etc. Causes sickle cell anemia',
    'Not listed in letter form on uniprot listed as alpha, beta etc. Normal form of haemoglobin',
    'Not sure what organism protein is taken from, not stated in original text',
    'Numerous forms of lipoxygenase for pea',
    'Numerous forms of lipoxygenase for soybean',
    'Numerous subunits available, not clear which have be analysed in original test',
    'Only one form found, perhaps same one in different locations',
    'Only one form of protein listed',
    'Only one subunit (alpha)',
    'Only one subunit (beta)',
    'Only one type of crotoxin can be found on uniprot',
    'Only one type of myoglobin available for horse on uniprot',
    'Only one type of myoglobin available for sperm whale on uniprot',
    'only one type of pancreatic lipase is available on Uniprot',
    'Only protein available is for S.aureus, not availble for individual strains',
    'Only sequence for myrosinase listed',
    'Phanerochaete chrysosporium is a taxonomic synonym for Chyrsosporin lignorum / Sporotrichum pruinosum',
    'Phanerochaete chrysosporium is a taxonomic synonym for Chyrsosporin lignorum / Sporotrichum pruinosum; multiple forms of protein listed',
    'precursor',
    'Presume this is correct form, all others displayed are lysozyme like proteins',
    'Protein available for numerous strains of E.coli',
    'Protein available for numerous strains of E.coli. Second reference http://www.jbc.org/content/246/13/4234.full.pdf',
    'Protein is available in many isoenzyme forms',
    'Protein on Uniprot but not for specific strain listed',
    'Protein on Uniprot but not for specific strain listed; multiple forms available',
    'second reference http://www.ncbi.nlm.nih.gov/pmc/articles/PMC389434/',
    'Second reference http://www.sciencedirect.com/science/article/pii/0005279570901479',
    'The only protein variant listed on Uniprot',
    'there are two chains, heavy and light',
    'There is a A1 and A2 form of this protein',
    'Three proteins available for this species.',
    'two different protein isoforms were analysed; two different pI values were determined: Not clear which sequence corresponds to which isoform',
    'Two forms of protein available',
    'Two Forms of protein available (A+B)',
    'Two forms of protein listed',
    'Two forms of the protein available, not sure which one was used for the experiment',
    'two isoforms available',
    'Two possible proteins located in diferent cellular compartments: http://www.uniprot.org/uniprot/P00506 (mitochondrial)  and http://www.uniprot.org/uniprot/P00503 (cytoplasmic)',
    'two sequences available, not clear which one coresponds to each subunit',
    'two types of protein A & B',
    'Unknown Polymerase Subunit; multiple subunits available on Uniprot',
    'Unknown yeast organism',
    'Unreviewed',
    'Unsure on species of the monkey'
  ]
};
