(ns pip-db.test.views.advanced
  (:use [clojure.test])
  (:require [pip-db.views.advanced :as dut]))

(deftest advanced
  (testing "Page contents is correct"
    (is (= (dut/advanced)
           (str "<!DOCTYPE html>\n<html class=\"no-js\" lang=\"en\"><head><meta"
                " charset=\"utf-8\"><meta content=\"IE=edge,chrome=1\" http-equ"
                "iv=\"X-UA-Compatible\"><meta content=\"width=device-width, ini"
                "tial-scale=1\" name=\"viewport\"><meta content=\"Protein Isoel"
                "ectric Point Database.\" name=\"msapplication-tooltip\"><title"
                ">pip-db Advanced Search</title><link href=\"/css/styles.css\" "
                "rel=\"stylesheet\" type=\"text/css\"><script src=\"/js/moderni"
                "zr-2.7.0.min.js\" type=\"text/javascript\"></script><script>(f"
                "unction(a,e,f,g,b,c,d){a.GoogleAnalyticsObject=b;a[b]=a[b]||fu"
                "nction(){(a[b].q=a[b].q||[]).push(arguments)};a[b].l=1*new Dat"
                "e;c=e.createElement(f);d=e.getElementsByTagName(f)[0];c.async="
                "1;c.src=g;d.parentNode.insertBefore(c,d)})(window,document,\"s"
                "cript\",\"//www.google-analytics.com/analytics.js\",\"ga\");ga"
                "(\"create\",\"UA-47069255-1\",\"pip-db.org\");ga(\"send\",\"pa"
                "geview\");\n</script></head><body><div class=\"navbar navbar-f"
                "ixed-top navbar-default\"><div class=\"container\"><div class="
                "\"navbar-header\"><button class=\"navbar-toggle\" data-target="
                "\"navbar-collapse\" data-toggle=\"collapse\" type=\"button\"><"
                "span class=\"icon-bar\"></span><span class=\"icon-bar\"></span"
                "><span class=\"icon-bar\"></span></button><a class=\"navbar-br"
                "and\" href=\"/\">pip-db</a></div><div class=\"navbar-collapse "
                "collapse\"><ul class=\"nav navbar-nav navbar-right\"><li><a hr"
                "ef=\"/login\">Login</a></li></ul></div></div></div><div id=\"w"
                "rap\"><div class=\"container\"><div class=\"page-title\"><div "
                "class=\"page-title-inner\"><h3>Advanced Search</h3></div><hr><"
                "/div><div class=\"advsearch\"><form action=\"/s\" id=\"as\" me"
                "thod=\"GET\"><div class=\"row\"><div class=\"col-md-12\"><h4>F"
                "ind proteins with...</h4></div></div><div class=\"row\"><div c"
                "lass=\"col-md-2\"><label for=\"q\">all of these words:</label>"
                "</div><div class=\"col-md-6\"><input autocomplete=\"off\" name"
                "=\"q\" type=\"text\"></div><div class=\"col-md-4\"><div class="
                "\"info\">Find proteins with names that contain these keywords<"
                "/div></div></div><div class=\"row\"><div class=\"col-md-2\"><l"
                "abel for=\"q_eq\">this exact word or phrase:</label></div><div"
                " class=\"col-md-6\"><input autocomplete=\"off\" name=\"q_eq\" "
                "type=\"text\"></div><div class=\"col-md-4\"><div class=\"info"
                "\">Type exact phrases to match in protein names.</div></div></"
                "div><div class=\"row\"><div class=\"col-md-2\"><label for=\"q_"
                "any\">any of these words:</label></div><div class=\"col-md-6\""
                "><input autocomplete=\"off\" name=\"q_any\" type=\"text\"></di"
                "v><div class=\"col-md-4\"><div class=\"info\">Select proteins "
                "from a range of keywords.</div></div></div><div class=\"row\">"
                "<div class=\"col-md-2\"><label for=\"q_ne\">none of these word"
                "s:</label></div><div class=\"col-md-6\"><input autocomplete=\""
                "off\" name=\"q_ne\" type=\"text\"></div><div class=\"col-md-4"
                "\"><div class=\"info\">Exclude proteins which contain these ke"
                "ywords.</div></div></div><div class=\"row\"><div class=\"col-m"
                "d-2\"><label for=\"q_s\">source:</label></div><div class=\"col"
                "-md-6\"><input autocomplete=\"off\" name=\"q_s\" type=\"text\""
                "></div><div class=\"col-md-4\"><div class=\"info\">Enter the L"
                "atin binomial or common names.</div></div></div><div class=\"r"
                "ow\"><div class=\"col-md-2\"><label for=\"q_l\">location:</lab"
                "el></div><div class=\"col-md-6\"><input autocomplete=\"off\" n"
                "ame=\"q_l\" type=\"text\"></div><div class=\"col-md-4\"><div c"
                "lass=\"info\">Enter the location or organ.</div></div></div><d"
                "iv class=\"row\"><div class=\"col-md-12\"><h4>Then narrow resu"
                "lts by...</h4></div></div><div class=\"row\"><div class=\"col-"
                "md-2\"><label for=\"ec1\">enzyme commission number:</label></d"
                "iv><div class=\"col-md-6\"><div style=\"display: table; width:"
                " 100%;\"><div style=\"display: table-cell; padding-right: 16px"
                ";\"><input autocomplete=\"off\" name=\"ec1\" type=\"text\"></d"
                "iv><div style=\"display: table-cell; padding-right: 16px;\"><i"
                "nput autocomplete=\"off\" name=\"ec2\" type=\"text\"></div><di"
                "v style=\"display: table-cell; padding-right: 16px;\"><input a"
                "utocomplete=\"off\" name=\"ec3\" type=\"text\"></div><div styl"
                "e=\"display: table-cell;\"><input autocomplete=\"off\" name=\""
                "ec4\" type=\"text\"></div></div></div><div class=\"col-md-4\">"
                "<div class=\"info\">Enter one or more categories for the EC.</"
                "div></div></div><div class=\"row\"><div class=\"col-md-2\"><la"
                "bel for=\"pi-min\">isoelectric point:</label></div><div class="
                "\"col-md-6\"><div style=\"display: table; width: 100%;\"><div "
                "style=\"display: table-cell;\"><input autocomplete=\"off\" nam"
                "e=\"pi_l\" type=\"text\"></div><div style=\"display: table-cel"
                "l; width:40px; padding-right: 6px;padding-left: 6px;text-align"
                ": center;\">to</div><div style=\"display: table-cell;\"><input"
                " autocomplete=\"off\" name=\"pi_h\" type=\"text\"></div></div>"
                "</div><div class=\"col-md-4\"><div class=\"info\">Enter an exa"
                "ct or range of isoelectric points.</div></div></div><div class"
                "=\"row\"><div class=\"col-md-2\"><label for=\"location\">molec"
                "ular weight:</label></div><div class=\"col-md-6\"><div style="
                "\"display: table; width: 100%;\"><div style=\"display: table-c"
                "ell;\"><input autocomplete=\"off\" name=\"mw_l\" type=\"text\""
                "></div><div style=\"display: table-cell; width:40px; padding-r"
                "ight: 6px; padding-left: 6px;text-align: center;\">to</div><di"
                "v style=\"display: table-cell;\"><input autocomplete=\"off\" n"
                "ame=\"mw_h\" type=\"text\"></div></div></div><div class=\"col-"
                "md-4\"><div class=\"info\">Enter an exact or range of molecula"
                "r weights.</div></div></div><div class=\"row\"><div class=\"co"
                "l-md-2\"><label for=\"m\">experimental method:</label></div><d"
                "iv class=\"col-md-6\"><select name=\"m\"><option>Analytical ge"
                "l isoelectric focusing</option><option>Analytical isoelectric "
                "focusing</option><option>Carrier-free isoelectric focusing</op"
                "tion><option>Column isoelectric focusing</option><option>Densi"
                "ty gradient isoelectric focusing</option><option>Disc electrop"
                "horesis</option><option>Disc gel electrophoresis</option><opti"
                "on>Electrofocusing</option><option>Electrophoresis</option><op"
                "tion>Electrostatic Focusing</option><option>Gel electrophoresi"
                "s</option><option>Gel isoelectric focusing</option><option>Iso"
                "electric density gradient electrophoresis</option><option>Isoe"
                "lectric focusing in polyacrylamide gel</option><option>Isoelec"
                "tric focusing in polyacrylamide gels</option><option>Isoelectr"
                "ic focusing on acrylamide gel</option><option>Isoelectric Focu"
                "sing with a Carrier Ampholyte</option><option>Isoelectric focu"
                "sing</option><option>Isoelectric fractionation</option><option"
                ">Isoelectrofocusing</option><option>LKB apparatus</option><opt"
                "ion>LKB electrofocusing apparatus</option><option>Measurement "
                "with an antimony microelectrode</option><option>Microisoelectr"
                "ic focusing on polyacrylamide gel</option><option>Polyacrylami"
                "de disc electrophoresis</option><option>Polyacrylamide gel ele"
                "ctrofucusing</option><option>Polyacrylamide gel isoelectric fo"
                "cusing</option><option>Preparative isoelectric focusing</optio"
                "n><option>SDS disc electrophoresis</option><option>SDS gel ele"
                "ctrophoresis</option><option>Stationary electrolysis</option><"
                "option>Thin-layer isoelectric focusing</option><option>Vesterb"
                "erg and Svensson method</option></select></div><div class=\"co"
                "l-md-4\"><div class=\"info\">Select the method which was used "
                "to determine the result</div></div></div><div class=\"row\"><d"
                "iv class=\"col-md-2\"><label for=\"t_l\">temperature:</label><"
                "/div><div class=\"col-md-6\"><div style=\"display: table; widt"
                "h: 100%;\"><div style=\"display: table-cell;\"><input autocomp"
                "lete=\"off\" name=\"t_l\" type=\"text\"></div><div style=\"dis"
                "play: table-cell; width:40px; padding-right: 6px;padding-left:"
                " 6px;text-align: center;\">to</div><div style=\"display: table"
                "-cell;\"><input autocomplete=\"off\" name=\"t_h\" type=\"text"
                "\"></div></div></div><div class=\"col-md-4\"><div class=\"info"
                "\">Enter an exact or range of temperatures.</div></div></div><"
                "div class=\"row\"><div class=\"col-md-2 col-md-offset-6\"><but"
                "ton class=\"btn btn-success pull-right\" name=\"action\" type="
                "\"submit\" value=\"advanced\">Advanced Search</button></div></"
                "div></form></div></div></div><div class=\"navbar navbar-defaul"
                "t navbar-bottom\"><div class=\"container\"><div class=\"navbar"
                "-header\"><button class=\"navbar-toggle\" data-target=\"navbar"
                "-collapse\" data-toggle=\"collapse\" type=\"button\"><span cla"
                "ss=\"icon-bar\"></span><span class=\"icon-bar\"></span><span c"
                "lass=\"icon-bar\"></span></button></div><div class=\"navbar-co"
                "llapse collapse\"><ul class=\"nav navbar-nav\"><li><a href=\"#"
                "\">About</a></li><li><a href=\"#\">Contact</a></li></ul><ul cl"
                "ass=\"nav navbar-nav navbar-right\"><li><a href=\"#\">Terms</a"
                "></li><li><a href=\"#\">Privacy</a></li></ul></div></div></div"
                "><script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.10.2/j"
                "query.min.js\" type=\"text/javascript\"></script><script>windo"
                "w.jQuery || document.write('<script src=\"/js/jquery-1.10.2.mi"
                "n.js\"><\\/script>');</script><script src=\"/js/bootstrap-3.0."
                "1.min.js\" type=\"text/javascript\"></script><script src=\"/js"
                "/main.js\" type=\"text/javascript\"></script><script src=\"/js"
                "/moment.min.js\" type=\"text/javascript\"></script><script>$(f"
                "unction(){var e=function(b){var c={};b.forEach(function(a){c[a"
                ".name]=a.value});return c},d=$(\"#as\"),f=e(d.serializeArray()"
                ");d.submit(function(b){b.preventDefault();b=e(d.serializeArray"
                "());var c={},a;for(a in b)f[a]!==b[a]&&(c[a]=b[a]);window.loca"
                "tion=d.attr(\"action\")+\"?\"+$.param(c)})});\n</script></body"
                "></html>")))))
