(ns pip-db.test.views.index
  (:use clojure.test)
  (:require [pip-db.views.index :as dut]))

(deftest index
  (testing "Page contents"
    (is (= (dut/index)
           (str "<!DOCTYPE html>\n<html class=\"no-js\" lang=\"en\"><head><meta"
                " charset=\"utf-8\"><meta content=\"IE=edge,chrome=1\" http-equ"
                "iv=\"X-UA-Compatible\"><meta content=\"width=device-width, ini"
                "tial-scale=1\" name=\"viewport\"><meta content=\"Protein Isoel"
                "ectric Point Database.\" name=\"msapplication-tooltip\"><title"
                ">pip-db </title><link href=\"/css/styles.css\" rel=\"styleshee"
                "t\" type=\"text/css\"><script src=\"/js/modernizr-2.7.0.min.js"
                "\" type=\"text/javascript\"></script><script>(function(a,e,f,g"
                ",b,c,d){a.GoogleAnalyticsObject=b;a[b]=a[b]||function(){(a[b]."
                "q=a[b].q||[]).push(arguments)};a[b].l=1*new Date;c=e.createEle"
                "ment(f);d=e.getElementsByTagName(f)[0];c.async=1;c.src=g;d.par"
                "entNode.insertBefore(c,d)})(window,document,\"script\",\"//www"
                ".google-analytics.com/analytics.js\",\"ga\");ga(\"create\",\"U"
                "A-47069255-1\",\"pip-db.org\");ga(\"send\",\"pageview\");\n</s"
                "cript></head><body><div class=\"navbar navbar-fixed-top navbar"
                "-invisible\"><div class=\"container\"><div class=\"navbar-head"
                "er\"><button class=\"navbar-toggle\" data-target=\"navbar-coll"
                "apse\" data-toggle=\"collapse\" type=\"button\"><span class=\""
                "icon-bar\"></span><span class=\"icon-bar\"></span><span class="
                "\"icon-bar\"></span></button><a class=\"navbar-brand\" href=\""
                "/\">pip-db</a></div><div class=\"navbar-collapse collapse\"><u"
                "l class=\"nav navbar-nav navbar-right\"><li><a href=\"/login\""
                ">Login</a></li></ul></div></div></div><div id=\"wrap\"><div cl"
                "ass=\"container\"><div class=\"row\"><div class=\"search col-m"
                "d-8 col-md-offset-2 text-center\"><h1 class=\"logo\">pip-db</h"
                "1><form action=\"/s\" method=\"GET\"><div id=\"qp\"><table cel"
                "lpadding=\"0\" cellspacing=\"0\"><tbody><tr><td><input autocom"
                "plete=\"off\" id=\"q\" name=\"q\" type=\"text\"></td><td id=\""
                "h\"><strong>?</strong></td></tr></tbody></table></div><div cla"
                "ss=\"btn-row\"><a class=\"btn btn-primary\" href=\"/advanced\""
                " id=\"search-browse\">Advanced</a><button class=\"btn btn-succ"
                "ess\" id=\"search-submit\">Search</button></div></form></div><"
                "/div></div></div><div class=\"navbar navbar-default navbar-bot"
                "tom\"><div class=\"container\"><div class=\"navbar-header\"><b"
                "utton class=\"navbar-toggle\" data-target=\"navbar-collapse\" "
                "data-toggle=\"collapse\" type=\"button\"><span class=\"icon-ba"
                "r\"></span><span class=\"icon-bar\"></span><span class=\"icon-"
                "bar\"></span></button></div><div class=\"navbar-collapse colla"
                "pse\"><ul class=\"nav navbar-nav\"><li><a href=\"#\">About</a>"
                "</li><li><a href=\"#\">Contact</a></li></ul><ul class=\"nav na"
                "vbar-nav navbar-right\"><li><a href=\"#\">Terms</a></li><li><a"
                " href=\"#\">Privacy</a></li></ul></div></div></div><script src"
                "=\"//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"
                "\" type=\"text/javascript\"></script><script>window.jQuery || "
                "document.write('<script src=\"/js/jquery-1.10.2.min.js\"><\\/s"
                "cript>');</script><script src=\"/js/bootstrap-3.0.1.min.js\" t"
                "ype=\"text/javascript\"></script><script src=\"/js/main.js\" t"
                "ype=\"text/javascript\"></script><script src=\"/js/moment.min."
                "js\" type=\"text/javascript\"></script><script>$(function(){$("
                "\"#q\").focus()});$(\"#q\").focus(function(){$(\"#qp\").addCla"
                "ss(\"active\")});$(\"#q\").blur(function(){$(\"#qp\").removeCl"
                "ass(\"active\")});\n</script></body></html>")))))
