(ns pip-db.test.views.login
  (:use clojure.test)
  (:require [pip-db.views.login :as dut]))

(deftest login
  (testing "Page contents"
    (is (= (dut/login)
           (str "<!DOCTYPE html>\n<html class=\"no-js\" lang=\"en\"><head><meta"
                " charset=\"utf-8\"><meta content=\"IE=edge,chrome=1\" http-equ"
                "iv=\"X-UA-Compatible\"><meta content=\"width=device-width, ini"
                "tial-scale=1\" name=\"viewport\"><meta content=\"Protein Isoel"
                "ectric Point Database.\" name=\"msapplication-tooltip\"><title"
                ">pip-db Sign in</title><link href=\"/css/styles.css\" rel=\"st"
                "ylesheet\" type=\"text/css\"><style>body{background:#eee;paddi"
                "ng:40px auto}.form-signin{max-width:330px;padding:15px;margin:"
                "0 auto}.form-signin .checkbox{font-weight:normal}.form-signin "
                ".form-control{position:relative;font-size:16px;height:auto;pad"
                "ding:10px;-webkit-box-sizing:border-box;-moz-box-sizing:border"
                "-box;box-sizing:border-box}.form-signin .form-control:focus{z-"
                "index:2}.form-signin input[type=\"text\"]{margin-bottom:-1px;b"
                "order-bottom-left-radius:0;border-bottom-right-radius:0}.form-"
                "signin input[type=\"password\"]{margin-bottom:10px;border-top-"
                "left-radius:0;border-top-right-radius:0}</style><script src=\""
                "/js/modernizr-2.7.0.min.js\" type=\"text/javascript\"></script"
                "><script>(function(a,e,f,g,b,c,d){a.GoogleAnalyticsObject=b;a["
                "b]=a[b]||function(){(a[b].q=a[b].q||[]).push(arguments)};a[b]."
                "l=1*new Date;c=e.createElement(f);d=e.getElementsByTagName(f)["
                "0];c.async=1;c.src=g;d.parentNode.insertBefore(c,d)})(window,d"
                "ocument,\"script\",\"//www.google-analytics.com/analytics.js\""
                ",\"ga\");ga(\"create\",\"UA-47069255-1\",\"pip-db.org\");ga(\""
                "send\",\"pageview\");\n</script></head><body><div id=\"wrap\">"
                "<div class=\"container\"><form action=\"/login\" class=\"form-"
                "signin\" method=\"post\"><h2 class=\"form-signin-heading\">Log"
                "in</h2><input autocomplete=\"off\" class=\"form-control\" name"
                "=\"user\" placeholder=\"Email address\" type=\"text\"><input c"
                "lass=\"form-control\" name=\"pass\" placeholder=\"Password\" t"
                "ype=\"password\"><label class=\"checkbox\"><input type=\"check"
                "box\" value=\"remember-me\">Remember me</input></label><div st"
                "yle=\"display: table; width: 100%;\"><div style=\"display: tab"
                "le-cell; width: 50%; padding-right: 8px;\"><button class=\"btn"
                " btn-lg btn-block btn-primary\" name=\"action\" value=\"regist"
                "er\">Register</button></div><div style=\"display: table-cell; "
                "width: 50%; padding-left: 8px;\"><button class=\"btn btn-lg bt"
                "n-block btn-success\" name=\"action\" type=\"submit\" value=\""
                "login\">Sign in</button></div></div></form></div></div><script"
                " src=\"//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.mi"
                "n.js\" type=\"text/javascript\"></script><script>window.jQuery"
                " || document.write('<script src=\"/js/jquery-1.10.2.min.js\"><"
                "\\/script>');</script><script src=\"/js/bootstrap-3.0.1.min.js"
                "\" type=\"text/javascript\"></script><script src=\"/js/main.js"
                "\" type=\"text/javascript\"></script><script src=\"/js/moment."
                "min.js\" type=\"text/javascript\"></script></body></html>")))))
