(ns pip-db.test.views.upload
  (:use clojure.test)
  (:require [pip-db.views.upload :as dut]))

(deftest upload
  (testing "Page contents"
    (is (= (dut/upload)
           (str "<!DOCTYPE html>\n<html class=\"no-js\" lang=\"en\"><head><meta char"
                "set=\"utf-8\"><meta content=\"IE=edge,chrome=1\" http-equiv=\"X-UA-"
                "Compatible\"><meta content=\"width=device-width, initial-scale"
                "=1\" name=\"viewport\"><meta content=\"Protein Isoelectric Poi"
                "nt Database.\" name=\"msapplication-tooltip\"><title>pip-db Up"
                "load</title><link href=\"/css/styles.css\" rel=\"stylesheet\" "
                "type=\"text/css\"><script src=\"/js/modernizr-2.7.0.min.js\" t"
                "ype=\"text/javascript\"></script><script>(function(a,e,f,g,b,c"
                ",d){a.GoogleAnalyticsObject=b;a[b]=a[b]||function(){(a[b].q=a["
                "b].q||[]).push(arguments)};a[b].l=1*new Date;c=e.createElement"
                "(f);d=e.getElementsByTagName(f)[0];c.async=1;c.src=g;d.parentN"
                "ode.insertBefore(c,d)})(window,document,\"script\",\"//www.goo"
                "gle-analytics.com/analytics.js\",\"ga\");ga(\"create\",\"UA-47"
                "069255-1\",\"pip-db.org\");ga(\"send\",\"pageview\");\n</scrip"
                "t></head><body><div class=\"navbar navbar-fixed-top navbar-def"
                "ault\"><div class=\"container\"><div class=\"navbar-header\"><"
                "button class=\"navbar-toggle\" data-target=\"navbar-collapse\""
                " data-toggle=\"collapse\" type=\"button\"><span class=\"icon-b"
                "ar\"></span><span class=\"icon-bar\"></span><span class=\"icon"
                "-bar\"></span></button><a class=\"navbar-brand\" href=\"/\">pi"
                "p-db</a></div><div class=\"navbar-collapse collapse\"><ul clas"
                "s=\"nav navbar-nav navbar-right\"><li><a href=\"/login\">Login"
                "</a></li></ul></div></div></div><div id=\"wrap\"><div class=\""
                "container\"><div class=\"page-title\"><div class=\"page-title-"
                "inner\"><h3>Add new data</h3></div><hr></div><div class=\"advs"
                "earch\"><form action=\"/upload\" enctype=\"multipart/form-data"
                "\" method=\"POST\"><div class=\"row\"><div class=\"col-md-12\""
                "><h4>1. Upload new data from file...</h4></div></div><div clas"
                "s=\"row\"><div class=\"col-md-12\"><input name=\"f\" type=\"fi"
                "le\"></div></div><div class=\"row\"><div class=\"col-md-12\"><"
                "div class=\"info\">Accepted file formats: .xls, .xlsx, .csv</d"
                "iv></div></div><hr><div class=\"row\"><div class=\"col-md-12\""
                "><h4>2. Or add a new record...</h4></div></div><div class=\"ro"
                "w\"><div class=\"col-md-2\"><label for=\"words-all\">protein n"
                "ame:</label></div><div class=\"col-md-6\"><input id=\"name\" t"
                "ype=\"text\"></div><div class=\"col-md-4\"><div class=\"info\""
                ">Enter the exact name of the protein.</div></div></div><div cl"
                "ass=\"row\"><div class=\"col-md-2\"><label for=\"source\">sour"
                "ce:</label></div><div class=\"col-md-6\"><input id=\"source\" "
                "type=\"text\"></div><div class=\"col-md-4\"><div class=\"info"
                "\">Enter the Latin binomial or common names.</div></div></div>"
                "<div class=\"row\"><div class=\"col-md-2\"><label for=\"locati"
                "on\">location:</label></div><div class=\"col-md-6\"><input id="
                "\"location\" type=\"text\"></div><div class=\"col-md-4\"><div "
                "class=\"info\">Enter the location or organ.</div></div></div><"
                "div class=\"row\"><div class=\"col-md-2\"><label for=\"locatio"
                "n\">enzyme commission number:</label></div><div class=\"col-md"
                "-6\"><div style=\"display: table; width: 100%;\"><div style=\""
                "display: table-cell; padding-right: 16px;\"><input id=\"ec1\" "
                "type=\"text\"></div><div style=\"display: table-cell; padding-"
                "right: 16px;\"><input id=\"ec2\" type=\"text\"></div><div styl"
                "e=\"display: table-cell; padding-right: 16px;\"><input id=\"ec"
                "3\" type=\"text\"></div><div style=\"display: table-cell;\"><i"
                "nput id=\"ec4\" type=\"text\"></div></div></div><div class=\"c"
                "ol-md-4\"><div class=\"info\">Enter the E.C.</div></div></div>"
                "<div class=\"row\"><div class=\"col-md-2\"><label for=\"pi-min"
                "\">isoelectric point:</label></div><div class=\"col-md-6\"><di"
                "v style=\"display: table; width: 100%;\"><div style=\"display:"
                " table-cell;\"><input id=\"pi-min\" type=\"text\"></div><div s"
                "tyle=\"display: table-cell; width:40px; padding-right: 6px;pad"
                "ding-left: 6px;text-align: center;\">to</div><div style=\"disp"
                "lay: table-cell;\"><input id=\"pi-max\" type=\"text\"></div></"
                "div></div><div class=\"col-md-4\"><div class=\"info\">Enter an"
                " exact or range of isoelectric points.</div></div></div><div c"
                "lass=\"row\"><div class=\"col-md-2\"><label for=\"location\">m"
                "olecular weight:</label></div><div class=\"col-md-6\"><div sty"
                "le=\"display: table; width: 100%;\"><div style=\"display: tabl"
                "e-cell;\"><input id=\"mw-min\" type=\"text\"></div><div style="
                "\"display: table-cell; width:40px; padding-right: 6px; padding"
                "-left: 6px;text-align: center;\">to</div><div style=\"display:"
                " table-cell;\"><input id=\"mw-max\" type=\"text\"></div></div>"
                "</div><div class=\"col-md-4\"><div class=\"info\">Enter an exa"
                "ct or range of molecular weights.</div></div></div><div class="
                "\"row\"><div class=\"col-md-2\"><label for=\"location\">experi"
                "mental method:</label></div><div class=\"col-md-6\"><select><o"
                "ption>Analytical gel isoelectric focusing</option><option>Anal"
                "ytical isoelectric focusing</option><option>Carrier-free isoel"
                "ectric focusing</option><option>Column isoelectric focusing</o"
                "ption><option>Density gradient isoelectric focusing</option><o"
                "ption>Disc electrophoresis</option><option>Disc gel electropho"
                "resis</option><option>Electrofocusing</option><option>Electrop"
                "horesis</option><option>Electrostatic Focusing</option><option"
                ">Gel electrophoresis</option><option>Gel isoelectric focusing<"
                "/option><option>Isoelectric density gradient electrophoresis</"
                "option><option>Isoelectric focusing in polyacrylamide gel</opt"
                "ion><option>Isoelectric focusing in polyacrylamide gels</optio"
                "n><option>Isoelectric focusing on acrylamide gel</option><opti"
                "on>Isoelectric Focusing with a Carrier Ampholyte</option><opti"
                "on>Isoelectric focusing</option><option>Isoelectric fractionat"
                "ion</option><option>Isoelectrofocusing</option><option>LKB app"
                "aratus</option><option>LKB electrofocusing apparatus</option><"
                "option>Measurement with an antimony microelectrode</option><op"
                "tion>Microisoelectric focusing on polyacrylamide gel</option><"
                "option>Polyacrylamide disc electrophoresis</option><option>Pol"
                "yacrylamide gel electrofucusing</option><option>Polyacrylamide"
                " gel isoelectric focusing</option><option>Preparative isoelect"
                "ric focusing</option><option>SDS disc electrophoresis</option>"
                "<option>SDS gel electrophoresis</option><option>Stationary ele"
                "ctrolysis</option><option>Thin-layer isoelectric focusing</opt"
                "ion><option>Vesterberg and Svensson method</option></select></"
                "div><div class=\"col-md-4\"><div class=\"info\">Select the met"
                "hod which was used to determine the result</div></div></div><d"
                "iv class=\"row\"><div class=\"col-md-2\"><label for=\"temp-min"
                "\">temperature:</label></div><div class=\"col-md-6\"><div styl"
                "e=\"display: table; width: 100%;\"><div style=\"display: table"
                "-cell;\"><input id=\"temp-min\" type=\"text\"></div><div style"
                "=\"display: table-cell; width:40px; padding-right: 6px;padding"
                "-left: 6px;text-align: center;\">to</div><div style=\"display:"
                " table-cell;\"><input id=\"temp-max\" type=\"text\"></div></di"
                "v></div><div class=\"col-md-4\"><div class=\"info\">Enter an e"
                "xact or range of temperatures.</div></div></div><div class=\"r"
                "ow\"><div class=\"col-md-2 col-md-offset-6\"><button class=\"b"
                "tn btn-primary pull-right\" name=\"action\" type=\"submit\" va"
                "lue=\"upload\">Submit</button></div></div></form></div></div><"
                "/div><div class=\"navbar navbar-default navbar-bottom\"><div c"
                "lass=\"container\"><div class=\"navbar-header\"><button class="
                "\"navbar-toggle\" data-target=\"navbar-collapse\" data-toggle="
                "\"collapse\" type=\"button\"><span class=\"icon-bar\"></span><"
                "span class=\"icon-bar\"></span><span class=\"icon-bar\"></span"
                "></button></div><div class=\"navbar-collapse collapse\"><ul cl"
                "ass=\"nav navbar-nav\"><li><a href=\"#\">About</a></li><li><a "
                "href=\"#\">Contact</a></li></ul><ul class=\"nav navbar-nav nav"
                "bar-right\"><li><a href=\"#\">Terms</a></li><li><a href=\"#\">"
                "Privacy</a></li></ul></div></div></div><script src=\"//ajax.go"
                "ogleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\" type=\"te"
                "xt/javascript\"></script><script>window.jQuery || document.wri"
                "te('<script src=\"/js/jquery-1.10.2.min.js\"><\\/script>');</s"
                "cript><script src=\"/js/bootstrap-3.0.1.min.js\" type=\"text/j"
                "avascript\"></script><script src=\"/js/main.js\" type=\"text/j"
                "avascript\"></script><script src=\"/js/moment.min.js\" type=\""
                "text/javascript\"></script></body></html>")))))
