#!/usr/bin/env node

/*
 * Prints a given message to console if env.debug is set.
 *
 * @param m Debugging message
 */
function debug(m) {
  if (env.debug)
    console.log('debug: ' + m);
}

/*
 * Prints a given error message to console and quits. Note this function does
 * not return.
 *
 * @param m Error message
 */
function fatal(m) {
  console.log('fatal: ' + m);
  process.exit(1);
}

/*
 * A tuple object.
 *
 * @param isHeader 1 for header tuple, else 0
 */
function Tuple(isHeader) {

  /* Return boolean true with probability (chance * 100)% */
  function rchance(chance) {
    return Math.random() < chance;
  }

  /* Return random entry from array */
  function rentry(array) {
    return env.payload[array][Math.floor(Math.random() * (array.length + 1))];
  }

  /* Return random integer in range low to high */
  function rint(low, high) {
    return Math.floor(Math.random() * (high - low + 1) + low);
  }

  /* Generate a random string of length characters */
  function rstring(length) {
    var string = '';
    var space = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' +
        'abcdefghijklmnopqrstuvwxyz' +
        '01234567890';

    for (var i = 0; i < length; i++)
      string += space.charAt(rint(0, space.length));

    return string;
  }

  /* Generate a random E.C. string */
  function rec() {
    return (rint(1, 3) + '.' +
            rint(1, 10) + '.' +
            rint(1, 20) + '.' +
            rint(1, 120));
  }

  /* Generate a random Latin binomial */
  function rbinomial() {
    var genus = rentry('latin');
    var species = rentry('latin');

    return genus + ' ' + species;
  }

  /* Generate a random molecular weight */
  function rmw() {
    return rint(23, 150) * 1000;
  }

  /* Generate a random isoelectric point */
  function rpi() {
    return (Math.random() * 14).toFixed(2);
  }

  if (isHeader) {
    /* Generate header titles */
    this.p = {
      'dataset' : 'Dataset',
      'ec' : 'E.C.',
      'protein' : 'Protein',
      'alt' : 'Alternative name(s)',
      'source' : 'Source',
      'organ' : 'Organ',
      'mw' : 'M.W',
      'subno' : 'Subunut No.',
      'submw' : 'Subunut M.W',
      'isoenzymes' : 'No. of Iso-enzymes',
      'piMax' : 'pI Maximum',
      'piRangeMin' : 'pI Range min',
      'piRangeMax' : 'pI Range max',
      'piMajor' : 'pI value of major component',
      'pi' : 'pI',
      'temp' : 'Temperature',
      'method' : 'Method',
      'valid' : 'Valid sequence(s) available',
      'sequence' : 'Protein Sequence',
      'species' : 'Species Taxonomy',
      'full' : 'Full Text',
      'abstract' : 'Abstract',
      'pubmed' : 'PubMed',
      'notes' : 'Notes'
    };

  } else {

    this.p = {
      'dataset' : '',
      'ec' : '',
      'protein' : '',
      'alt' : '',
      'source' : '',
      'organ' : '',
      'mw' : '',
      'subno' : '',
      'submw' : '',
      'isoenzymes' : '',
      'piMax' : '',
      'piRangeMin' : '',
      'piRangeMax' : '',
      'piMajor' : '',
      'pi' : '',
      'temp' : '',
      'method' : '',
      'valid' : '',
      'sequence' : '',
      'species' : '',
      'full' : '',
      'abstract' : '',
      'pubmed' : '',
      'notes' : ''
    };

    this.p['dataset'] = rentry('datasets');

    this.p['ec'] = rchance(0.8) ? rec() : '';

    this.p['protein'] = rentry('proteins');

    this.p['alt'] = rchance(0.9) ? rentry('proteins') : '';

    this.p['source'] = rbinomial();

    this.p['organ'] = rchance(0.6) ? rentry('organs') : '';

    this.p['mw'] = rchance(0.9) ? rmw() : '';

    if (rchance(0.3)) {
      this.p['subno'] = rint(1, 148);
      this.p['submw'] = rmw();
    }

    this.p['isoenzymes'] = rchance(0.9) ? rint(1, 10000) : '';

    if (rchance(0.95)) {
      if (rchance(0.8))
        this.p['pi'] = rpi();
      else {
        if (rchance(0.5))
          this.p['piMax'] = rpi();
        else if (rchance(0.5))
          this.p['piMajor'] = rpi();
        else {
          this.p['piRangeMin'] = rpi();
          this.p['piRangeMax'] = rpi();
        }
      }
    }

    if (rchance(0.8)) {
      if (rchance(0.7))
        this.p['temp'] = rint(10, 30) + 'C';
      else {
        this.p['temp'] = rint(10, 20) + ' - ' + rint(21, 30) + 'C';
      }
    }

    this.p['method'] = rchance(0.8) ? rentry('methods') : 'Not available';

    this.p['valid'] = rentry('validsequences');

    this.p['sequence'] = rchance(0.6) ?
      'http://www.ncbi.nlm.nih.gov/protein/' + rstring(8) : '';

    this.p['species'] = rchance(0.95) ?
      'http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?lvl=0&id='
      + rstring(8) : '';

    if (rchance(0.8)) {
      if (rchance(0.95))
        this.p['full'] = 'http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1177738/pdf/biochemj' + rstring(8);
      else
        this.p['abstract'] = 'http://www.sciencedirect.com/science/article/pii/' + rstring(16);
    }

    if (rchance(0.9))
      this.p['pubmed'] = 'http://www.ncbi.nlm.nih.gov/pubmed/' + rstring(8);

    if (rchance(0.02))
      this.p['notes'] = rentry('notes');
  }
}

/*
 * @return Tab-seperated format tuple
 */
Tuple.prototype.toCSV = function() {
  var string = '';

  for (var key in this.p) {
    string += this.p[key] + '\t';
  }

  return string;
}

/* Initialise command line parameter parsing */
var argv = require('optimist')
    .default('c', './pngrc')
    .default('p', './payload.js')
    .default('s', 512)
    .default('o', './dataset.csv')
    .argv;

/* Set args from long options */
if (argv.conf !== undefined)
  argv.c = argv.conf;
if (argv.payload !== undefined)
  argv.p = argv.payload;
if (!isNaN(argv.size))
  argv.s = argv.size;
if (argv.output !== undefined)
  argv.o = argv.output;

/* Setup our environment */
var env = {
  debug: false,
  includes: {
    payload: argv.p,
    conf: argv.c
  },
  output: argv.o
};

global.Configuration = {
  format: 'CSV',
  size: 512
}

/* Global variable set TRUE if executed with '-d' or '--debug' flags */
env.debug = argv.d || argv.debug ? true : false;

 /* Let's print some useful environmental info before getting stuck in */
debug('using payload file: \'' + env.includes.payload + '\'');
debug('using configuration file: \'' + env.includes.conf + '\'');
debug('writing output to file: \'' + env.output + '\'');

/* Fire up the file system */
var fs = require('fs');

/* Load the files in our list of includes. Any error is here is considered
 * fatal */
for (var file in env.includes) {
  try {
    require(env.includes[file]);
  } catch (e) {
    fatal('failed to open \'' + env.includes[file] + '\'!');
  }
}

/* Set out local environment from external files */
env.conf = Configuration;
env.payload = Payload;

/* Last minute sanity checks */
if (env.payload === undefined) {
  fatal('no payload found!');
}

if (env.conf === undefined) {
  fatal('no configuration found!');
}

/* Print some more useful debugging info */
debug('generating ' + env.conf.size + ' records');
debug('output file format: ' + Configuration.format);

/* Instantiate dataset */
var dataset = '';

/* Populate dataset */
for (var i = 0; i <= env.conf.size; i++) {
  var t = new Tuple(i === 0 ? 1 : 0);

  switch (env.conf.format) {
  case 'CSV':
    dataset += t.toCSV() + '\n';
    break;
  }
}

/* Write the dataset to file */
fs.writeFile(env.output, dataset, function(err) {
  if (err)
    fatal('failed to write to \'' + env.output + '\'!');
});
