<?php require_once( $_SERVER['PHP_ROOT'] . 'init.php' );

/*
 * The search results page. Only accessed indirectly, i.e. when referred to
 * within the website by a link generated by this PHP controller.
 *
 * TODO: Handle the error-situation when a user accesses this link with a valid
 * GET query set.
 */

function fetch_all( $resource ) {
	$results = array();

	while ( $r = mysql_fetch_assoc( $resource ) ) {
		$row = array();

		foreach ( $r as $k )
			array_push( $row, $k );

		array_push( $results, $row );
	}

	return $results;
}

function get_results_page_url( $num ) {
	$current_url = pip_history_get_current();;

	if ( $num > 1 ) {
		$start_at_number = ( $num - 1 ) * Pip_Search::ResultsPerPage;

		if ( preg_match( '/&start=\d+/', $current_url ) ) {
			$url = preg_replace( '/&start=\d+/',
					     '&start=' . $start_at_number,
					     $current_url );
		} else {
			$url = $current_url .'&start=' . $start_at_number;
		}

	} else {
		$url = preg_replace( '/&start=\d+/', '', $current_url );
	}

	return $url;
}

function get_results_page( $num ) {
	return array(
		"num" => $num,
		"href" => get_results_page_url( $num )
		);
}

function get_found_rows() {
	$resource = pip_db_query( "SELECT FOUND_ROWS() AS `count`" );
	$array = mysql_fetch_assoc( $resource );
	return $array['count'];
}

$start_time = microtime( true );

$starting_at = pip_get_isset( GetVariables::StartAt ) ? pip_get( GetVariables::StartAt ) : 0;
$ending_at = $starting_at + Pip_Search::ResultsPerPage;

/* Perform the query */
$query = PipQueryBuilder::build( new PipSearchQueryValues(), $starting_at );
$resource = pip_db_query( $query->get_mysql_query() );

if ( !$resource )
	throw new Exception( 'Failed to query database!' );

$results_count = get_found_rows();

$results = fetch_all( $resource );

/* Calculate page numbers and whatnot */
$num_of_pages = ceil( $results_count / Pip_Search::ResultsPerPage );
$current_page = $starting_at / Pip_Search::ResultsPerPage + 1;

/* Generate pagination hrefs */
$pages = array();
$starting_page = max( 1, $current_page - Pip_Search::MaxPaginationLinks / 2 );

$ending_page = min( $num_of_pages + 1,
		    $starting_page + Pip_Search::MaxPaginationLinks);

for ( $i = $starting_page; $i < $ending_page; $i++ ) {
	$url = get_results_page_url( $i );

	array_push( $pages, array( "num" => $i, "href" => $url ) );
}

$end_time = microtime( true );

$elapsed_time = $end_time - $start_time;

$content = array(
	/*
	 * The search text.
	 */
	"search_text" => pip_get( GetVariables::Query ),
	/*
	 * The elapsed time for the query (in seconds).
	 */
	"elapsed_time" => $elapsed_time,
	/*
	 * (optional)
	 * Href to download the results.
	 */
	"download" => "http://127.0.0.1",
	/*
	 * An array of results. This can be empty if no results were found.
	 */
	"results" => $results,
	/*
	 * The number of results returned.
	 */
	"results_count" => $results_count,
	/*
	 * (optional)
	 * Href to pagination links, if we returned more than one page.
	 */
	"pages" => $pages,
	/*
	 * (optional)
	 * If the results span multiple pages, set this to the page number
	 * currently being displayed.
	 */
	"current_page" => get_results_page( $current_page ),
	"first_page" => get_results_page( 1 ),
	"last_page" => get_results_page( $num_of_pages )
	);

$template = new Pip_Template( 'search' );
$template->render( $content );
