#!/bin/bash
#
# Generates a description of the website build in a PHP script.
#
# This bundles a bunch of useful information about the current website build
# into a single variable in a generated PHP file.
#
topsrcdir=pip-db

# The path (relative to topsrcdir) of the PHP file to generate
out=www/lib/build-summary.php

# Look up the top source directory. Do this by traversing up the directory tree
# from the current directory. If we haven't found the top directory by the time
# we reach root (/), fail.
get_source_directory() {
	local root=""

	while [[ "$(pwd)" != "/" ]]; do
		if [[ "${PWD##*/}" = "$topsrcdir" ]]; then
			echo "$(pwd)"
			return
		fi
		cd ..
	done

	echo "fatal: Unable to locate source directory." >&2

	# If we can't find a real path to change to, then return something bogus
	# so that cd will fail and the script will terminate.
	echo "/not/a/real/path"
}

set -e

cd $(get_source_directory) 2>/dev/null

echo -n "Generating '$out'... "

cat <<EOF > "$out"
<?php
/*
 * Website status file. Generated by '$0'
 * at Mon Dec 23 15:47:37 GMT 2013.
 *
 * DO NOT EDIT THIS FILE BY HAND.
 */
\$_BUILD_SUMMARY = array(
	'Build date' => '$(date)',
	'Build host' => '$(hostname)',
	'Build user' => '$(whoami)',
	'Git release' => '$(git describe)',
	'Git branch' => '$(git symbolic-ref HEAD 2>/dev/null | sed 's/refs\/heads\///')',
	'Git HEAD' => '$(git rev-parse HEAD)'
	);
EOF

echo "done"
